################################################################################
dmesg
dmesg -f


################################################################################
sysctl fs.inotify.max_user_watches
sysctl fs.inotify.max_user_watches=1048576

free -h

lscpu
lsof
lspci
lsusb
picocom -b 115200 /dev/ttyUSB0

uname -a
uptime