[[snippets]]
  description = "config user name"
  command = "git config --global user.name <name=Example>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "config user email"
  command = "git config --global user.email <email=example@example.com>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "disable ssl verification"
  command = "git config --global http.sslVerify false"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "set http proxy"
  command = "git config --global http.proxy http://<proxy>:<port>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "unset setting"
  command = "git config --global --unset <setting=http.proxy>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "list all config"
  command = "git config -l"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "initialize a repository"
  command = "git init"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "clone a repository"
  command = "git clone --recurse-submodules <url>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "add all modified or new files"
  command = "git add -A"
  tag = ["git", "gaa"]
  output = ""

[[snippets]]
  description = "show status"
  command = "git status"
  tag = ["git", "gst"]
  output = ""

[[snippets]]
  description = "commit"
  command = "git commit -m <message=''>"
  tag = ["git", "gcmsg"]
  output = ""

[[snippets]]
  description = "amend last commit"
  command = "git commit --amend -m <message=''>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "amend last commit without change message"
  command = "git commit --amend --no-edit"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "add files and commit"
  command = "git commit --all -m <message=''>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "pull changes"
  command = "git pull"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "pull changes and rebase local changes on top"
  command = "git pull --rebase"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "execute pull in a directory"
  command = "git -C <directory> pull"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "push changes"
  command = "git push"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "soft reset to a commit"
  command = "git reset <dst-commit>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "hard reset to a commit"
  command = "git reset --hard <dst-commit>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "group several commits together"
  command = "git reset --soft HEAD~<number-of-commits> && git commit -m <message=''>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "search for files"
  command = "git ls-files | grep <file-pattern>"
  tag = ["git", "gfg"]
  output = ""

[[snippets]]
  description = "list local branches"
  command = "git branch"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "list remote-tracking branches and local branches"
  command = "git branch -a"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "list remote-tracking branches"
  command = "git branch -r"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "remove/delete a branch"
  command = "git branch -d <name>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "force remove/delete a branch"
  command = "git branch -D <name>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "rename branch"
  command = "git branch -m <old> <new>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "filter branches"
  command = "git branch -l <pattern='feature/*'>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "mark a file as removed/deleted"
  command = "git rm -- <file>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "mark a directory as removed/deleted"
  command = "git rm -r -- <directory>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "reset content of a file"
  command = "git checkout -- <file>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "switch to a branch"
  command = "git checkout <branch=master>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "create and switch to a new branch"
  command = "git checkout -b <branch>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "view changes relative to the staging area"
  command = "git diff"
  tag = ["git", "gd"]
  output = ""

[[snippets]]
  description = "view changes relative to the staging area of a specific file"
  command = "git diff -- <file>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "view changes of the staging area"
  command = "git diff --staged"
  tag = ["git", "gds"]
  output = ""

[[snippets]]
  description = "view changes of a file between commits"
  command = "git diff <old=HEAD~3> <new=HEAD> -- <file>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "view changes relative to the staging area"
  command = "git difftool"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "view changes of the staging area"
  command = "git difftool --staged"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "display commit log"
  command = "git log --graph"
  tag = ["git", "glgg"]
  output = ""

[[snippets]]
  description = "display commit log with changed files"
  command = "git log --graph --name-status"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "display commit log with changed files"
  command = "git log --graph --stat"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "search for text in all commits/history"
  command = "git log -S <text> --source --all"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "push current changes to temporary stack"
  command = "git stash"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "pop changes from temporary stack"
  command = "git stash pop"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "drop latest changes from temporary stack"
  command = "git stash drop"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "list temporary stack"
  command = "git stash list"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "update submodule code"
  command = "git submodule update --recursive"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "initialize submodule code"
  command = "git submodule update --recursive --init"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "merge branch to current branch"
  command = "git merge <branch=bugfix>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "squash merge branch to current branch"
  command = "git merge --squash <branch=bugfix>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "reset working directory"
  command = "git clean -xdf"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "show reflog"
  command = "git reflog"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "start local webserver for curent repository"
  command = "git instaweb"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "stop webserver"
  command = "git instaweb stop"
  tag = ["git"]
  output = ""
