build-opensuse-tumbleweed:
  stage: build
  image: opensuse/tumbleweed
  script:
    - zypper --non-interactive install git make python python-xml python-urllib3 ansible
    - mkdir ~/Documents ~/Downloads
    - make env
    - make CICD=1 system-opensuse-tumbleweed
    - make CICD=1 system-opensuse-tumbleweed
