build-opensuse-tumbleweed:
  stage: build
  image: opensuse/tumbleweed
  script:
    - zypper --non-interactive install make python python-xml ansible
    - mkdir ~/Documents ~/Downloads
    - make env
    - make cicd
