build-opensuse-tumbleweed:
  stage: build
  image: opensuse/tumbleweed
  script:
    - zypper --non-interactive install git make python python-xml python-urllib3 ansible
    - mkdir ~/Documents ~/Downloads
    - make env
    - make CICD=1 system-opensuse-tumbleweed
    - make CICD=1 system-opensuse-tumbleweed

build-ubuntu-18.04:
  stage: build
  image: ubuntu:18.04
  script:
    - apt update
    - apt --assume-yes install git make python ansible
    - mkdir ~/Documents ~/Downloads
    - make env
    - make CICD=1 system-ubuntu-18.04
    - make CICD=1 system-ubuntu-18.04
