build-opensuse-tumbleweed:
  stage: build
  image: opensuse/tumbleweed
  script:
    - env
    - zypper --non-interactive install sudo git make python python-xml python-urllib3 ansible
    - echo "root:r00T15243" | chpasswd
    - useradd -g users -m -s /bin/bash -u 1000 testuser
    - su -l -c "mkdir ~/Documents ~/Downloads" - testuser
    - su -l -c "make -C \"$CI_PROJECT_DIR\" env" - testuser
    - su -l -c "make -C \"$CI_PROJECT_DIR\" CICD=1 system-opensuse-tumbleweed" - testuser
    - su -l -c "make -C \"$CI_PROJECT_DIR\" CICD=1 system-opensuse-tumbleweed" - testuser
