build-opensuse-tumbleweed:
  stage: build
  image: opensuse/tumbleweed
  script:
    - zypper --non-interactive install make python python-xml ansible
    - mkdir ~/Documents ~/Downloads
    - make env
    - make cicd

build-ubuntu-18.04:
  stage: build
  image: ubuntu:18.04
  script:
    - apt --assume-yes install make python python-xml ansible
    - mkdir ~/Documents ~/Downloads
    - make env
    - make cicd
