---
- name: Creating Directory Structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.ssh
    - ~/work/media/images
    - ~/work/media/videos
    - ~/work/others
    - ~/work/programming/projects
    - ~/work/programming/sources
    - ~/work/tmp
    - ~/work/tools
    - ~/work/vms
    - ~/work/warehouse

- name: Moving ~/Downloads And ~/Documents
  block:
    - name: Moving Files
      command: mv "{{ item.src }}" "{{ item.dst }}"
      args:
        creates: "{{ item.dst }}"
      with_items:
        - { src : "~/Documents", dst : "~/work/documents" }
        - { src : "~/Downloads", dst : "~/work/downloads" }

    - name: Creating Symlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.symlink }}"
        state: link
      with_items:
        - { src : "~/work/documents", symlink : "~/Documents" }
        - { src : "~/work/downloads", symlink : "~/Downloads" }

- name: Downloading FireFox And ThunderBird
  block:
    - command: wget -O firefox.tar.bz2 "{{ urls.mozilla.firefox }}"
      args:
        chdir: ~/work/tools
        creates: firefox.tar.bz2
    - command: wget -O thunderbird.tar.bz2 "{{ urls.mozilla.thunderbird }}"
      args:
        chdir: ~/work/tools
        creates: thunderbird.tar.bz2

- name: Configuring Git
  block:
    - stat:
        path: ~/.gitconfig
      register: p
    - block:
        - git_config:
            name: "{{ item.key }}"
            scope: global
            value: "{{ item.value }}"
          with_items:
            - { key: "user.name",            value: "{{ git.user.name }}" }
            - { key: "user.email",           value: "{{ git.user.email }}" }
            - { key: "user.useConfigOnly",   value: true }
            - { key: "alias.ggrep",          value: "grep --break --heading --line-number" }
            - { key: "oh-my-zsh.hide-dirty", value: 1 }
      when: not p.stat.exists

- name: Oh-My-Zsh
  block:
    - git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh
    - copy:
        src=files/zshrc
        dest=~/.zshrc
        force=no
    - user:
        name="{{ ansible_user }}"
        shell=/bin/zsh
      become: true
      become_user: root

- name: fzf
  block:
    - git:
        repo: https://github.com/junegunn/fzf
        dest: ~/.fzf
    - shell: ~/.fzf/install --all --no-fish

- name: Adding frequently used commands in history
  script: files/commands
