[[snippets]]
  description = "display kernel tracepoints or USDT probes and their formats"
  command = "tplist -v"
  tag = []
  output = ""

[[snippets]]
  description = "print a histogram of allocation sizes passed to kmalloc"
  command = "argdist -H 'p::__kmalloc(u64 size):u64:size'"
  tag = []
  output = ""

[[snippets]]
  description = "print a frequency count of how many times process 1005 called malloc with an allocation size of 16 bytes"
  command = "argdist -p 1005 -C 'p:c:malloc(size_t size):size_t:size:size==16'"
  tag = []
  output = ""

[[snippets]]
  description = "print a histogram of results (sizes) returned by read() in process 1005"
  command = "argdist -p 1005 -H 'r:c:read()'"
  tag = []
  output = ""

[[snippets]]
  description = "summarize block device I/O latency as a histogram"
  command = "biolatency"
  tag = []
  output = ""

[[snippets]]
  description = "summarize block device I/O latency as a histogram per disk"
  command = "biolatency -D"
  tag = []
  output = ""

[[snippets]]
  description = "summarize block device I/O latency as a histogram including OS queued time"
  command = "biolatency -Q"
  tag = []
  output = ""

[[snippets]]
  description = "trace block device I/O activities"
  command = "biosnoop"
  tag = []
  output = ""

[[snippets]]
  description = "trace block device I/O activities including OS queued time"
  command = "biosnoop -Q"
  tag = []
  output = ""

[[snippets]]
  description = "top block device I/O by process"
  command = "biotop"
  tag = []
  output = ""

[[snippets]]
  description = "block device I/O size histogram per process"
  command = "bitesize"
  tag = []
  output = ""

[[snippets]]
  description = "summarize btrfs operation latency"
  command = "btrfsdist"
  tag = []
  output = ""

[[snippets]]
  description = "summarize btrfs operation latency for process 181"
  command = "btrfsdist -p 181"
  tag = []
  output = ""

[[snippets]]
  description = "trace common btrfs file operations slower than a threshold"
  command = "btrfsslower"
  tag = []
  output = ""

[[snippets]]
  description = "trace common btrfs file operations slower than a threshold for process 185"
  command = "btrfsslower -p 185"
  tag = []
  output = ""

[[snippets]]
  description = "show page cache hit/miss statistics"
  command = "cachestat"
  tag = []
  output = ""

[[snippets]]
  description = "show page cache hit/miss statistics per process"
  command = "cachetop"
  tag = []
  output = ""

[[snippets]]
  description = "summarize object allocations in c language of process 145"
  command = "uobjnew"
  tag = []
  output = ""

[[snippets]]
  description = "summarize object allocations in java language of process 145"
  command = "uobjnew"
  tag = []
  output = ""

[[snippets]]
  description = "summarize on-CPU time per task as a histogram"
  command = "cpudist"
  tag = []
  output = ""

[[snippets]]
  description = "summarize on-CPU time per task as a histogram for process 73"
  command = "cpudist -p 73"
  tag = []
  output = ""

[[snippets]]
  description = "summarize off-CPU time per task as a histogram"
  command = "cpudist -O"
  tag = []
  output = ""

[[snippets]]
  description = "sample CPU run queues and calculate unclaimed idle CPU"
  command = "cpuunclaimed"
  tag = []
  output = ""

[[snippets]]
  description = "trace PostgreSQL queries slower than 1ms"
  command = "dbslower postgres"
  tag = []
  output = ""

[[snippets]]
  description = "trace MySQL queries slower than 30ms"
  command = "dbslower mysql -m 30"
  tag = []
  output = ""

[[snippets]]
  description = "display a histogram of PostgreSQL query latencies"
  command = "dbstat postgres"
  tag = []
  output = ""

[[snippets]]
  description = "trace failed directory entry cache lookups"
  command = "dcsnoop"
  tag = []
  output = ""

[[snippets]]
  description = "directory entry cache lookups stats"
  command = "dcstat"
  tag = []
  output = ""

[[snippets]]
  description = "detect potential deadlocks in a running binary by tracing pthread mutex lock and unlock calls for process 181"
  command = "deadlock 181"
  tag = []
  output = ""

[[snippets]]
  description = "trace all direct reclaim of memory"
  command = "drsnoop"
  tag = []
  output = ""

[[snippets]]
  description = "trace all exec() syscalls"
  command = "execsnoop"
  tag = []
  output = ""

[[snippets]]
  description = "trace exec() syscalls that have 'main' in command line"
  command = "execsnoop -n main"
  tag = []
  output = ""

[[snippets]]
  description = "trace all process termination"
  command = "exitsnoop"
  tag = []
  output = ""

[[snippets]]
  description = "trace the lifespan of short-lived files"
  command = "filelife"
  tag = []
  output = ""

[[snippets]]
  description = "trace the lifespan of short-lived files for process 167"
  command = "filelife -p 167"
  tag = []
  output = ""

[[snippets]]
  description = "trace sync file I/O slower than 10ms"
  command = "fileslower"
  tag = []
  output = ""

[[snippets]]
  description = "trace sync file I/O slower than 10ms for process 149"
  command = "fileslower -p 149"
  tag = []
  output = ""

[[snippets]]
  description = "top file reads and writes by process"
  command = "filetop"
  tag = []
  output = ""

[[snippets]]
  description = "top file reads and writes for process 181"
  command = "filetop -p 181"
  tag = []
  output = ""

[[snippets]]
  description = "count kernel fns starting with 'vfs'"
  command = "funccount 'vfs_*'"
  tag = []
  output = ""

[[snippets]]
  description = "count all malloc() calls in libc for process 185"
  command = "funccount -p 185 c:malloc"
  tag = []
  output = ""

[[snippets]]
  description = "count 'read*' calls in the ./test binary"
  command = "funccount ./test:read*"
  tag = []
  output = ""

[[snippets]]
  description = "time the do_sys_open() kernel function and print out as histogram"
  command = "funclatency do_sys_open"
  tag = []
  output = ""

[[snippets]]
  description = "time the vfs_read() kernel function and print out as histogram for process 181"
  command = "funclatency -p 181 vfs_read"
  tag = []
  output = ""

[[snippets]]
  description = "time the *printf family of functions and print out as histogram"
  command = "funclatency 'c:*printf'"
  tag = []
  output = ""

[[snippets]]
  description = "trace vfs_write calls slower than 1ms"
  command = "funcslower vfs_write"
  tag = []
  output = ""

[[snippets]]
  description = "trace open calls slower than 1ms for process 135"
  command = "funcslower -p 135 c:open"
  tag = []
  output = ""

[[snippets]]
  description = "show latency for getaddrinfo/gethostbyname calls"
  command = "gethostlatency"
  tag = []
  output = ""

[[snippets]]
  description = "show latency for getaddrinfo/gethostbyname calls for process 217"
  command = "gethostlatency -p 217"
  tag = []
  output = ""

[[snippets]]
  description = "show hard irq event time as histograms"
  command = "hardirqs -d"
  tag = []
  output = ""

[[snippets]]
  description = "summarize CPU cache references and misses by PID"
  command = "llcstat"
  tag = []
  output = ""

[[snippets]]
  description = "trace allocations and display a summary of 'leaked' (outstanding) allocations every 5 seconds for process 211"
  command = "memleak -p 211"
  tag = []
  output = ""

[[snippets]]
  description = "trace off-CPU stack time for process 217"
  command = "offcputime -p 217"
  tag = []
  output = ""

[[snippets]]
  description = "trace off-CPU stack time for 30 seconds and build flamegraph for process 217"
  command = "offcputime --folded -p 217 30 | flamegraph.pl > stack.svg"
  tag = []
  output = ""

[[snippets]]
  description = "trace all open() syscalls"
  command = "opensnoop"
  tag = []
  output = ""

[[snippets]]
  description = "trace all open() syscalls for process 223"
  command = "opensnoop -p 223"
  tag = []
  output = ""

[[snippets]]
  description = "count new processes via fork"
  command = "pidpersec"
  tag = []
  output = ""

[[snippets]]
  description = "profile stack traces at 49 Hertz for process 229"
  command = "profile -p 229"
  tag = []
  output = ""

[[snippets]]
  description = "profile stack traces at 49 Hertz for 30 seconds and build flamegraph for process 229"
  command = "profile --folded -p 229 30 | flamegraph.pl > stack.svg"
  tag = []
  output = ""

[[snippets]]
  description = "summarize run queue latency as a histogram by measuring the time a task spends waiting on a run queue for a turn on-CPU"
  command = "runqlat"
  tag = []
  output = ""

[[snippets]]
  description = "summarize run queue length as a histogram excluding the currently running threads"
  command = "runqlen"
  tag = []
  output = ""

[[snippets]]
  description = "show the time threads spending waiting on run queue higher than 10000us"
  command = "runqslower"
  tag = []
  output = ""

[[snippets]]
  description = "show soft irq event time as histograms"
  command = "softirqs -d"
  tag = []
  output = ""

[[snippets]]
  description = "count stacks for funcs matching tcp_send*"
  command = "stackcount 'tcp_send*'"
  tag = []
  output = ""

[[snippets]]
  description = "count stacks for malloc in 30 seconds and build flamegraph for process 185"
  command = "stackcount -p 185 --folded -D 30 c:malloc | flamegraph.pl > stack.svg"
  tag = []
  output = ""

[[snippets]]
  description = "trace all stat() syscalls"
  command = "statsnoop"
  tag = []
  output = ""

[[snippets]]
  description = "trace all sync() syscalls"
  command = "syncsnoop"
  tag = []
  output = ""

[[snippets]]
  description = "summarize syscall counts"
  command = "syscount"
  tag = []
  output = ""

[[snippets]]
  description = "summarize syscall counts for process 157"
  command = "syscount -p 157"
  tag = []
  output = ""

[[snippets]]
  description = "trace TCP accepts"
  command = "tcpaccept"
  tag = []
  output = ""

[[snippets]]
  description = "trace TCP connects"
  command = "tcpconnect"
  tag = []
  output = ""

[[snippets]]
  description = "trace TCP connects and show connection latency"
  command = "tcpconnlat"
  tag = []
  output = ""

[[snippets]]
  description = "trace TCP drops by the kernel"
  command = "tcpdrop"
  tag = []
  output = ""

[[snippets]]
  description = "trace TCP retransmits"
  command = "tcpretrans"
  tag = []
  output = ""

[[snippets]]
  description = "summarize TCP send and aggregate by subnet"
  command = "tcpsubnet"
  tag = []
  output = ""

[[snippets]]
  description = "summarize TCP send/recv throughput by host"
  command = "tcptop"
  tag = []
  output = ""

[[snippets]]
  description = "trace the open syscall and print a default trace message when entered"
  command = "trace do_sys_open"
  tag = []
  output = ""

[[snippets]]
  description = "trace the open syscall and print the filename being opened"
  command = """trace 'do_sys_open "%s", arg2'"""
  tag = []
  output = ""

[[snippets]]
  description = "count VFS calls vfs_*"
  command = "vfscount"
  tag = []
  output = ""

[[snippets]]
  description = "count some VFS calls"
  command = "vfsstat"
  tag = []
  output = ""
