[[snippets]]
  description = "list subvolume"
  command = "sudo btrfs subvolume list /"
  tag = []
  output = ""

[[snippets]]
  description = "force a sync of the filesystem"
  command = "sudo btrfs filesystem sync /"
  tag = []
  output = ""

[[snippets]]
  description = "show detailed information about internal filesystem usage"
  command = "sudo btrfs filesystem usage /"
  tag = []
  output = ""
