[[snippets]]
  description = "compile a c++ program"
  command = "g++ -std=c++17 -Wall -Wextra -Werror -O3 -pedantic -pthread -o main main.cpp"
  tag = []
  output = ""

[[snippets]]
  description = "print out assembly of c++ program"
  command = "g++ -S main.cpp"
  tag = []
  output = ""
