print -s "tar -cvSf archived.tar dir/"
print -s "tar -cvSf compressed.tar.xz --xz dir/"
print -s "tar -cvSf compressed.tar.gz --gzip dir/"
print -s "tar -cvSf compressed.tar.bz2 --bzip2 dir/"
print -s "tar -xvf archived.tar"
print -s "tar -xvf compressed.tar.xz --xz"
print -s "tar -xvf compressed.tar.gz --gzip"
print -s "tar -xvf compressed.tar.bz2 --bzip2"
print -s "tar -xvf archived.tar -C dir/"
