[[snippets]]
  description = "archive directory"
  command = "tar -cvSf {archived.tar} {dir}"
  tag = []
  output = ""

[[snippets]]
  description = "compress a directory"
  command = "tar -cvSf {compressed.tar.xz} --xz {dir}"
  tag = []
  output = ""

[[snippets]]
  description = "compress a directory"
  command = "tar -cvSf {compressed.tar.gz} --gzip {dir}"
  tag = []
  output = ""

[[snippets]]
  description = "compress a directory"
  command = "tar -cvSf {compressed.tar.bz2} --bzip2 {dir}"
  tag = []
  output = ""

[[snippets]]
  description = "de-archive a file"
  command = "tar -xvf {archived.tar}"
  tag = []
  output = ""

[[snippets]]
  description = "decompress a file"
  command = "tar -xvf {compressed.tar.xz} --xz"
  tag = []
  output = ""

[[snippets]]
  description = "decompress a file"
  command = "tar -xvf {compressed.tar.gz} --gzip"
  tag = []
  output = ""

[[snippets]]
  description = "decompress a file"
  command = "tar -xvf {compressed.tar.bz2} --bzip2"
  tag = []
  output = ""

[[snippets]]
  description = "de-archive a file to directory"
  command = "tar -xvf {archived.tar} -C {dir}"
  tag = []
  output = ""
