[[snippets]]
  description = "build an image from a Dockerfile"
  command = "docker build --tag name:tag ."
  tag = []
  output = ""

[[snippets]]
  description = "build an image from a Dockerfile in a directory"
  command = "docker build --tag name:tag directory"
  tag = []
  output = ""

[[snippets]]
  description = "build an image from an arbitrary Dockerfile with a directory"
  command = "docker build --tag name:tag -f new-dockerfile directory"
  tag = []
  output = ""

[[snippets]]
  description = "copy files/folders between a container and the local filesystem"
  command = "docker cp container-name:src dst"
  tag = []
  output = ""

[[snippets]]
  description = "copy files/folders between a container and the local filesystem"
  command = "docker cp dst container-name:src"
  tag = []
  output = ""

[[snippets]]
  description = "inspect changes to files or directories on a container’s filesystem"
  command = "docker diff container-name"
  tag = []
  output = ""

[[snippets]]
  description = "run a command in a new container"
  command = "docker run --env 'TERM=xterm' --init --tty --volume $(pwd):/code --workdir /code image bash"
  tag = []
  output = ""

[[snippets]]
  description = "run a command in a running container"
  command = "docker exec --tty --interactive --privileged container-name bash"
  tag = []
  output = ""

[[snippets]]
  description = "display detailed information on one or more containers"
  command = "docker container inspect container-name"
  tag = []
  output = ""

[[snippets]]
  description = "fetch the logs of a container"
  command = "docker logs container-name"
  tag = []
  output = ""

[[snippets]]
  description = "list port mappings or a specific mapping for the container"
  command = "docker port container-name"
  tag = []
  output = ""

[[snippets]]
  description = "remove all stopped containers"
  command = "docker container prune"
  tag = []
  output = ""

[[snippets]]
  description = "rename a container"
  command = "docker rename container-name new-name"
  tag = []
  output = ""

[[snippets]]
  description = "restart one or more containers"
  command = "docker restart container-name"
  tag = []
  output = ""

[[snippets]]
  description = "start one or more stopped containers"
  command = "docker start container-name"
  tag = []
  output = ""

[[snippets]]
  description = "stop one or more running containers"
  command = "docker stop container-name"
  tag = []
  output = ""

[[snippets]]
  description = "display the running processes of a container"
  command = "docker top container-name"
  tag = []
  output = ""

[[snippets]]
  description = "build an image from a Dockerfile"
  command = "docker build --tag name:tag ."
  tag = []
  output = ""

[[snippets]]
  description = "build an image from a Dockerfile in a directory"
  command = "docker build --tag name:tag directory"
  tag = []
  output = ""

[[snippets]]
  description = "build an image from an arbitrary Dockerfile with a directory"
  command = "docker build --tag name:tag -f new-dockerfile directory"
  tag = []
  output = ""

[[snippets]]
  description = "load an image from a tar archive or stdin"
  command = "docker load -i file.tar"
  tag = []
  output = ""

[[snippets]]
  description = "list images"
  command = "docker images"
  tag = []
  output = ""

[[snippets]]
  description = "remove unused images"
  command = "docker image prune"
  tag = []
  output = ""

[[snippets]]
  description = "pull an image or a repository from a registry"
  command = "docker pull image:tag"
  tag = []
  output = ""

[[snippets]]
  description = "push an image or a repository to a registry"
  command = "docker push"
  tag = []
  output = ""

[[snippets]]
  description = "remove one or more images"
  command = "docker rmi image"
  tag = []
  output = ""

[[snippets]]
  description = "save one or more images to a tar archive"
  command = "docker save -o file.tar image"
  tag = []
  output = ""

[[snippets]]
  description = "tag an image"
  command = "docker tag image image:tag"
  tag = []
  output = ""

[[snippets]]
  description = "display system-wide information"
  command = "docker info"
  tag = []
  output = ""

[[snippets]]
  description = "return low-level information on docker objects"
  command = "docker inspect object-id"
  tag = []
  output = ""

[[snippets]]
  description = "connect a container to a network"
  command = "docker network connect"
  tag = []
  output = ""

[[snippets]]
  description = "create a network"
  command = "docker network create network-name"
  tag = []
  output = ""

[[snippets]]
  description = "disconnect a container from a network"
  command = "docker network disconnect network-name container-name"
  tag = []
  output = ""

[[snippets]]
  description = "display detailed information on one or more networks"
  command = "docker network inspect"
  tag = []
  output = ""

[[snippets]]
  description = "list networks"
  command = "docker network ls"
  tag = []
  output = ""

[[snippets]]
  description = "remove all unused networks"
  command = "docker network prune"
  tag = []
  output = ""

[[snippets]]
  description = "remove one or more networks"
  command = "docker network rm"
  tag = []
  output = ""

[[snippets]]
  description = "list containers"
  command = "docker ps"
  tag = []
  output = ""

[[snippets]]
  description = "run a command in a new container"
  command = "docker run --env 'TERM=xterm' --init --tty --volume $(pwd):/code --workdir /code image bash"
  tag = []
  output = ""

[[snippets]]
  description = "list volumes"
  command = "docker volume ls"
  tag = []
  output = ""

[[snippets]]
  description = "remove all unused local volumes"
  command = "docker volume prune"
  tag = []
  output = ""

[[snippets]]
  description = "display detailed information on one or more volumes"
  command = "docker volume inspect"
  tag = []
  output = ""

[[snippets]]
  description = "export a container's filesystem as a tar archive"
  command = """docker export "$(docker create --name container-name image-name true)" > ubuntu-18.04.tar && docker rm container-name"""
  tag = []
  output = ""

[[snippets]]
  description = "lists containers"
  command = "docker-compose ps"
  tag = []
  output = ""

[[snippets]]
  description = "start containers for a service"
  command = "docker-compose up"
  tag = []
  output = ""

[[snippets]]
  description = "create and start containers for a service"
  command = "docker-compose up --build --renew-anon-volumes"
  tag = []
  output = ""

[[snippets]]
  description = "restarts all stopped and running services"
  command = "docker-compose restart service-name"
  tag = []
  output = ""

[[snippets]]
  description = "stops running containers without removing them"
  command = "docker-compose stop service-name"
  tag = []
  output = ""

[[snippets]]
  description = "starts existing containers for a service"
  command = "docker-compose start service-name"
  tag = []
  output = ""

[[snippets]]
  description = "displays log output from services"
  command = "docker-compose logs -f service-name"
  tag = []
  output = ""
