print -s "rsync --dry-run --delete --archive --recursive --progress --verbose srcdir/ dstdir"
print -s "rsync --delete --archive --recursive --progress --verbose srcdir/ dstdir"

print -s "find dir/ -type f -name '*.log'"
print -s "find dir/ -type f -name '.*'"
print -s "find dir/ -type f -empty -delete"
print -s "find dir/ -type f -executable"
print -s "find dir/ -type d -empty -delete"
print -s "find dir/ -user root"

print -s "mount"
print -s "mount -o loop file.iso dir"

print -s "chattr +i ~/.gitconfig"
print -s "chattr -i ~/.gitconfig"
print -s "lsattr ~/.gitconfig"

print -s "tree -d"
print -s "tree -f"
print -s "tree -h --du"
print -s "tree -h"
print -s "tree -L 3"
print -s "tree"

print -s "chmod +r file"
print -s "chmod -r file"
print -s "chmod +x file"
print -s "chmod -x file"
print -s "chmod 664 file"
print -s "chmod 755 script"
print -s "chmod 1755 suscript"

print -s "chown root file"
print -s "chown root: file"
print -s "chown :root file"
print -s "chown nobody: file"
print -s "chown nobody:nogroup file"

print -s "md5sum file"
print -s "sha1sum file"
print -s "sha256sum file"
print -s "sha512sum file"

print -s "cp src dst"
print -s "cp --archive src dst"
print -s "cp -a src dst"
print -s "mv src dst"
print -s "ln --symbolic --force --no-dereference src dst"
print -s "ln -sfn src dst"

print -s "dd bs=512k status=progress if=/dev/urandom of=/dev/null"
print -s "df -h"
print -s "lsblk"
print -s "sync"
