[[snippets]]
  description = "copy directory and delete extraneous files from dest dirs"
  command = "rsync --dry-run --delete --archive --recursive --progress --verbose srcdir/ dstdir"
  tag = []
  output = ""

[[snippets]]
  description = "merge directory to directory"
  command = "rsync --dry-run --archive --recursive --progress --verbose srcdir/ dstdir"
  tag = []
  output = ""

[[snippets]]
  description = "copy file to another file"
  command = "dd status=progress bs=512k if=/dev/urandom of=/dev/null"
  tag = []
  output = ""
