print -s "git config --global user.name 'Example'"
print -s "git config --global user.email 'example@example.com'"
print -s "git config --global http.proxy http://<proxy>:<port>"
print -s "git config --global --unset http.proxy"
print -s "git config --list"
print -s "git init"
print -s "git clone <url>"
print -s "git clone --recurse-submodules <url>"
print -s "git add ."
print -s "git add --all ."
print -s "git commit -m ''"
print -s "git commit --all -m ''"
print -s "git pull"
print -s "git pull --rebase"
print -s "git pull --squash"
print -s "git -C dir pull"
print -s "git push"
print -s "git reset <commit>"
print -s "git reset --hard <commit>"
print -s "git ls-files | grep a"
print -s "git branch"
print -s "git branch --remote"
print -s "git branch name"
print -s "git branch --delete name"
print -s "git branch -d name"
print -s "git branch --delete --force name"
print -s "git branch -D name"
print -s "git branch --move old new"
print -s "git branch -m old new"
print -s "git branch --list 'feature/*'"
print -s "git branch -l 'feature/*'"
print -s "git rm -- file"
print -s "git checkout -- file"
print -s "git checkout master"
print -s "git checkout -b branch"
print -s "git diff"
print -s "git diff --staged"
print -s "git diff HEAD~3 HEAD -- file.txt"
print -s "git difftool"
print -s "git difftool --staged"
print -s "git log"
print -s "git log --graph"
print -s "git stash"
print -s "git stash pop"
print -s "git stash drop"
print -s "git stash list"
print -s "git submodule update"
print -s "git submodule update --recursive"
print -s "git submodule update --recursive --init"
print -s "git merge bugfix"
print -s "git merge --squash bugfix"
print -s "git clean -df"
print -s "git clean -xdf"
print -s "git reflog"
print -s "git instaweb"

print -s "gst"
print -s "ga ."
print -s "gcmsg ''"
print -s "gd"
print -s "gfg"
print -s "glgg"
