[[snippets]]
  description = "compile packages and dependencies"
  command = "go build"
  tag = []
  output = ""

[[snippets]]
  description = "remove object files and cached files"
  command = "go clean"
  tag = []
  output = ""

[[snippets]]
  description = "print environment information"
  command = "go env"
  tag = []
  output = ""

[[snippets]]
  description = "reformat package sources"
  command = "go fmt './...'"
  tag = []
  output = ""

[[snippets]]
  description = "compile and run program"
  command = "go run"
  tag = []
  output = ""

[[snippets]]
  description = "report likely mistakes in packages"
  command = "go vet './...'"
  tag = []
  output = ""
