[[snippets]]
  description = "show overall status"
  command = "nmcli general status"
  tag = []
  output = ""

[[snippets]]
  description = "show network status"
  command = "nmcli networking"
  tag = []
  output = ""

[[snippets]]
  description = "get network connectivity state"
  command = "nmcli networking connectivity"
  tag = []
  output = ""

[[snippets]]
  description = "enable networking control"
  command = "nmcli networking on"
  tag = []
  output = ""

[[snippets]]
  description = "disable networking control"
  command = "nmcli networking off"
  tag = []
  output = ""

[[snippets]]
  description = "show radio switches status"
  command = "nmcli radio"
  tag = []
  output = ""

[[snippets]]
  description = "show wifi status"
  command = "nmcli radio wifi"
  tag = []
  output = ""

[[snippets]]
  description = "enable wifi"
  command = "nmcli radio wifi on"
  tag = []
  output = ""

[[snippets]]
  description = "disable wifi"
  command = "nmcli radio wifi off"
  tag = []
  output = ""

[[snippets]]
  description = "list all connection profiles"
  command = "nmcli connection"
  tag = []
  output = ""

[[snippets]]
  description = "activate a connection"
  command = "nmcli connection up <name>"
  tag = []
  output = ""

[[snippets]]
  description = "deactivate a connection"
  command = "nmcli connection down <name>"
  tag = []
  output = ""

[[snippets]]
  description = "show network interfaces"
  command = "nmcli device"
  tag = []
  output = ""

[[snippets]]
  description = "show detail network interfaces"
  command = "nmcli device show"
  tag = []
  output = ""

[[snippets]]
  description = "list all access points"
  command = "nmcli device wifi"
  tag = []
  output = ""

[[snippets]]
  description = "rescan all access points"
  command = "nmcli device wifi rescan"
  tag = []
  output = ""

[[snippets]]
  description = "connect to a wifi network"
  command = "nmcli device wifi connect <SSID-Name> password <wireless-password>"
  tag = []
  output = ""

[[snippets]]
  description = "create a wifi hotspot"
  command = "nmcli device wifi hotspot ssid <SSID> password <password>"
  tag = []
  output = ""

[[snippets]]
  description = "open TUI network manager"
  command = "nmtui"
  tag = []
  output = ""

[[snippets]]
  description = "list available interfaces"
  command = "sudo tcpdump -D"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets"
  command = "sudo tcpdump"
  tag = []
  output = ""

[[snippets]]
  description = "capture with less verbose output than default"
  command = "sudo tcpdump -q"
  tag = []
  output = ""

[[snippets]]
  description = "capture only 5 packets"
  command = "sudo tcpdump -c 5"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets for all interfaces"
  command = "sudo tcpdump -i any"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets with specified port"
  command = "sudo tcpdump -n dst port <port>"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets arriving at or departing from host"
  command = "sudo tcpdump -n host <host>"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets arriving at host"
  command = "sudo tcpdump -n dst host <host>"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets departing from host"
  command = "sudo tcpdump -n src host <host>"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets arriving at host at port 443"
  command = "sudo tcpdump -n 'dst host <host> and dst port 443'"
  tag = []
  output = ""

[[snippets]]
  description = "capture packets and save result to file"
  command = "sudo tcpdump -w <file=capture.cap>"
  tag = []
  output = ""

[[snippets]]
  description = "capture icmp package"
  command = "sudo tcpdump -v icmp"
  tag = []
  output = ""

[[snippets]]
  description = "show interface details"
  command = "ip addr"
  tag = []
  output = ""

[[snippets]]
  description = "show all routes"
  command = "ip route"
  tag = []
  output = ""

[[snippets]]
  description = "show current neighbor table in kernel"
  command = "ip neigh"
  tag = []
  output = ""

[[snippets]]
  description = "bring interface up"
  command = "ip link set <interface> up"
  tag = []
  output = ""

[[snippets]]
  description = "bring interface down"
  command = "ip link set <interface> down"
  tag = []
  output = ""

[[snippets]]
  description = "show all TCP connections"
  command = "ss --tcp --all --processes"
  tag = []
  output = ""

[[snippets]]
  description = "show all established TCP connections"
  command = "ss --tcp --processes"
  tag = []
  output = ""

[[snippets]]
  description = "issue and show DNS lookup progress"
  command = "dig <hostname>"
  tag = []
  output = ""

[[snippets]]
  description = "query DNS of a host"
  command = "nslookup <hostname>"
  tag = []
  output = ""

[[snippets]]
  description = "print the route packet goes through"
  command = "traceroute <host>"
  tag = []
  output = ""

[[snippets]]
  description = "open http server in python 2"
  command = "python -m SimpleHTTPServer 8080"
  tag = []
  output = ""

[[snippets]]
  description = "open http server in python 3"
  command = "python3 -m http.server 8080 --directory /tmp"
  tag = []
  output = ""
