[[snippets]]
  description = "list all processes"
  command = "ps aux"
  tag = []
  output = ""

[[snippets]]
  description = "list all processes in tree"
  command = "ps axjf"
  tag = []
  output = ""

[[snippets]]
  description = "display processes continuously"
  command = "top"
  tag = []
  output = ""

[[snippets]]
  description = "display processes continuously"
  command = "htop"
  tag = []
  output = ""
