print -s "cargo init"
print -s "cargo init --bin"
print -s "cargo build"
print -s "cargo build --release"
print -s "cargo run"
print -s "cargo run --release"
print -s "cargo test"
print -s "cargo clean"
print -s "cargo clean --release"
print -s "cargo fmt --all"
print -s "cargo doc"
print -s "cargo doc --release"
