print -s "snapper list-configs"
print -s "snapper list"
print -s "snapper create --description 'Snapshot'"
print -s "snapper create --cleanup-algorithm number --description 'Snapshot'"
print -s "snapper create --cleanup-algorithm number --userdata 'important=yes' --description 'Snapshot'"
