print -s "systemctl status"
print -s "systemctl status docker"
print -s "systemctl start docker"
print -s "systemctl stop docker"
print -s "systemctl restart docker"
print -s "systemctl enable docker"
print -s "systemctl disable docker"
print -s "systemctl edit docker"
print -s "systemctl cat docker"
