[[snippets]]
  description = "boot a container"
  command = "systemd-nspawn -b -M ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "run a command in container"
  command = "systemd-nspawn -a -M ubuntu-18.04 /bin/bash"
  tag = []
  output = ""
