[[snippets]]
  description = "open an interactive shell session in a container"
  command = "machinectl shell ubuntu-18.04 /bin/bash"
  tag = []
  output = ""

[[snippets]]
  description = "start a container as a system service"
  command = "machinectl start ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "open an interactive terminal login session in a container"
  command = "machinectl login ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "power off a container"
  command = "machinectl stop ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "reboot a container"
  command = "machinectl reboot ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "show runtime status information about a container"
  command = "machinectl status ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "bind mount a file/directory from host to container"
  command = "machinectl bind --read-only --mkdir container-name src dst"
  tag = []
  output = ""

[[snippets]]
  description = "copy file/directory from host to container"
  command = "machinectl copy-to container-name src dst"
  tag = []
  output = ""

[[snippets]]
  description = "copy file/directory from container to host"
  command = "machinectl copy-from container-name src dst"
  tag = []
  output = ""

[[snippets]]
  description = "enable a container to start as a system service at system boot"
  command = "machinectl enable ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "disable container from starting at boot time"
  command = "machinectl disable ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "list locally installed hidden images"
  command = "machinectl list-images"
  tag = []
  output = ""

[[snippets]]
  description = "list all locally installed images"
  command = "machinectl list-images --all"
  tag = []
  output = ""

[[snippets]]
  description = "remove hidden images"
  command = "machinectl clean"
  tag = []
  output = ""

[[snippets]]
  description = "remove all images"
  command = "machinectl clean --all"
  tag = []
  output = ""

[[snippets]]
  description = "export an image to tar file"
  command = "machinectl export-tar ubuntu-18.04 ubuntu-18.04.tar.xz"
  tag = []
  output = ""

[[snippets]]
  description = "import image from a tar file"
  command = "machinectl import-tar ubuntu-18.04.tar ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "import image from a filesystem"
  command = "machinectl import-fs directory ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "download image from URL"
  command = "machinectl pull-tar url image"
  tag = []
  output = ""

[[snippets]]
  description = "remove image"
  command = "machinectl remove ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "mark an image as read-only"
  command = "machinectl read-only ubuntu-18.04"
  tag = []
  output = ""

[[snippets]]
  description = "clone an image"
  command = "machinectl clone src dst"
  tag = []
  output = ""

[[snippets]]
  description = "rename an image"
  command = "machinectl rename old new"
  tag = []
  output = ""
