[[snippets]]
  description = "list all boots"
  command = "journalctl --list-boots"
  tag = []
  output = ""

[[snippets]]
  description = "follow system log"
  command = "journalctl --follow"
  tag = []
  output = ""

[[snippets]]
  description = "follow service log"
  command = "journalctl --follow --unit <service>"
  tag = []
  output = ""
