print -s "machinectl shell ubuntu-18.04 /bin/bash"
print -s "machinectl start ubuntu-18.04"
print -s "machinectl login ubuntu-18.04"
print -s "machinectl stop ubuntu-18.04"
print -s "machinectl reboot ubuntu-18.04"
print -s "machinectl status ubuntu-18.04"
print -s "machinectl bind --read-only --mkdir src dst"
print -s "machinectl copy-to src dst"
print -s "machinectl copy-from src dst"
print -s "machinectl enable ubuntu-18.04"
print -s "machinectl disable ubuntu-18.04"
print -s "machinectl list-images"
print -s "machinectl clean"
print -s "machinectl export-tar ubuntu-18.04 ubuntu-18.04.tar.xz"
print -s "machinectl import-tar ubuntu-18.04.tar ubuntu-18.04"
print -s "machinectl import-fs dir/ ubuntu-18.04"
print -s "machinectl remove ubuntu-18.04"
print -s "machinectl read-only ubuntu-18.04"
print -s "machinectl clone src dst"
print -s "machinectl rename old new"
