[[snippets]]
  description = "show system boot time"
  command = "systemd-analyze"
  tag = ["systemd-analyze", "systemd"]
  output = ""

[[snippets]]
  description = "show startup time for each unit"
  command = "systemd-analyze blame"
  tag = ["systemd-analyze", "systemd"]
  output = ""

[[snippets]]
  description = "print system startup time for each service in SVG"
  command = "systemd-analyze plot"
  tag = ["systemd-analyze", "systemd"]
  output = ""
