[[snippets]]
  description = "show kernel log"
  command = "dmesg"
  tag = []
  output = ""

[[snippets]]
  description = "show kernel log continuously"
  command = "dmesg -f"
  tag = []
  output = ""

[[snippets]]
  description = "show sysctl value"
  command = "sysctl fs.inotify.max_user_watches"
  tag = []
  output = ""

[[snippets]]
  description = "temporarily set sysctl value"
  command = "sysctl fs.inotify.max_user_watches=1048576"
  tag = []
  output = ""

[[snippets]]
  description = "show system memory status"
  command = "free -h"
  tag = []
  output = ""

[[snippets]]
  description = "show CPU info"
  command = "lscpu"
  tag = []
  output = ""

[[snippets]]
  description = "show open files"
  command = "lsof"
  tag = []
  output = ""

[[snippets]]
  description = "show PCI bus information"
  command = "lspci"
  tag = []
  output = ""

[[snippets]]
  description = "show USB bus information"
  command = "lsusb"
  tag = []
  output = ""

[[snippets]]
  description = "connect to serial port"
  command = "picocom -b 115200 /dev/ttyUSB0"
  tag = []
  output = ""

[[snippets]]
  description = "show system information"
  command = "uname -a"
  tag = []
  output = ""

[[snippets]]
  description = "show uptime"
  command = "uptime"
  tag = []
  output = ""

[[snippets]]
  description = "show disk io"
  command = "sudo iotop"
  tag = []
  output = ""

[[snippets]]
  description = "show network io per host name"
  command = "sudo iftop"
  tag = []
  output = ""

[[snippets]]
  description = "show network io per process"
  command = "sudo nethogs"
  tag = []
  output = ""

[[snippets]]
  description = "show devices and partitions io"
  command = "iostat -d 1"
  tag = []
  output = ""

[[snippets]]
  description = "show system io"
  command = "dstat -f"
  tag = []
  output = ""

[[snippets]]
  description = "show traces of the io traffic on block devices"
  command = "btrace /dev/sda"
  tag = []
  output = ""
