[[snippets]]
  description = "resolve hostname or ip address"
  command = "resolvectl query hostname-or-ip"
  tag = []
  output = ""

[[snippets]]
  description = "show DNS settings"
  command = "resolvectl status"
  tag = []
  output = ""
