print -s "sysctl fs.inotify.max_user_watches"
print -s "sysctl fs.inotify.max_user_watches=1048576"

print -s "dmesg"
print -s "dmesg --follow"
print -s "dmesg -f"

print -s "echo {0..3} | xargs mkdir"
print -s "du -h | sort -h"
print -s "free -h"
print -s "id3v2 -D **/*.mp3"
print -s "lscpu"
print -s "lsof"
print -s "lspci"
print -s "lsusb"
print -s "picocom -b 115200 /dev/ttyUSB0"
print -s "sleep 1"
print -s "tail -F file.log"
print -s "time cal"
print -s "uname -a"
print -s "uptime"
print -s "chroot ubuntu/ /bin/bash"
