[[snippets]]
  description = "view all users of a group"
  command = "getent group docker"
  tag = []
  output = ""

[[snippets]]
  description = "view user's groups"
  command = "groups root"
  tag = []
  output = ""

[[snippets]]
  description = "add user to group"
  command = "usermod -aG docker user"
  tag = []
  output = ""

[[snippets]]
  description = "view all groups in the system"
  command = "getent group"
  tag = []
  output = ""
