print -s "cat /proc/cmdline"
print -s "cat /proc/cpuinfo"
print -s "cat /proc/meminfo"
print -s "cat /proc/uptime"
print -s "cat /proc/version"
print -s "cat /proc/vmstat"
print -s "cat /etc/passwd"
print -s "cat /etc/group"
print -s "cat /etc/profile"
print -s "cat /etc/hosts"
print -s "cat /etc/resolv.conf"
print -s "cat /etc/hostname"

print -s "vim /etc/sysctl.d/99-sysctl.conf"
print -s "vim /etc/gitlab-runner/config.toml"
print -s "vim /etc/systemd/system/gitlab-runner.service"
print -s "vim ~/.ssh/config"
print -s "vim ~/.ssh/known_hosts"
print -s "vim ~/.curlrc"
print -s "vim ~/.gdbinit"
print -s "vim ~/.gitconfig"
print -s "vim ~/.hgrc"
print -s "vim ~/.wgetrc"
print -s "vim ~/.zshrc"
print -s "vim .git/config"
print -s "vim .gitignore"
print -s "vim .gitmodules"
print -s "vim Dockerfile"
print -s "vim Makefile"

print -s "date"
print -s "date '+%F.%H-%M-%S'"
print -s "date '+%Y-%m-%d_%H-%M-%S'"

print -s "seq 10"
print -s "seq 0 10"
print -s "seq 0 2 10"
print -s "seq --separator , 0 10"
print -s "seq -s , 0 10"
print -s "seq --equal-width 0 10"
print -s "seq -w 0 10"
