[[snippets]]
  description = "view kernel command line"
  command = "cat /proc/cmdline"
  tag = []
  output = ""

[[snippets]]
  description = "view cpu information"
  command = "cat /proc/cpuinfo"
  tag = []
  output = ""

[[snippets]]
  description = "view memory information"
  command = "cat /proc/meminfo"
  tag = []
  output = ""

[[snippets]]
  description = "view system uptime"
  command = "cat /proc/uptime"
  tag = []
  output = ""

[[snippets]]
  description = "view linux version"
  command = "cat /proc/version"
  tag = []
  output = ""

[[snippets]]
  description = "view virtual memory information"
  command = "cat /proc/vmstat"
  tag = []
  output = ""

[[snippets]]
  description = "view users"
  command = "cat /etc/passwd"
  tag = []
  output = ""

[[snippets]]
  description = "view groups"
  command = "cat /etc/group"
  tag = []
  output = ""

[[snippets]]
  description = "view shell profile"
  command = "cat /etc/profile"
  tag = []
  output = ""

[[snippets]]
  description = "view hosts/DNS mapping"
  command = "cat /etc/hosts"
  tag = []
  output = ""

[[snippets]]
  description = "view domain name servers"
  command = "cat /etc/resolv.conf"
  tag = []
  output = ""

[[snippets]]
  description = "view current hostname"
  command = "cat /etc/hostname"
  tag = []
  output = ""
