#!/bin/zsh

echo
echo -e "  \e[92mALT\e[0m  + \e[95mQ\e[0m : Temporarily hide current line"
echo
echo -e "  \e[93mCTRL\e[0m + \e[95mA\e[0m : Go to the beginning"
echo -e "  \e[93mCTRL\e[0m + \e[95mE\e[0m : Go to the end"
echo
echo -e "  \e[92mALT\e[0m  + \e[95mF\e[0m : Move to next word"
echo -e "  \e[92mALT\e[0m  + \e[95mB\e[0m : Move to previous word"
echo
echo -e "  \e[93mCTRL\e[0m + \e[95mU\e[0m : Cut the entire line"
echo -e "  \e[93mCTRL\e[0m + \e[95mK\e[0m : Cut the characters after the cursor"
echo
echo -e "  \e[93mCTRL\e[0m + \e[95mW\e[0m : Cut a word before the cursor"
echo -e "  \e[92mALT\e[0m  + \e[95mD\e[0m : Cut a word after the cursor"
echo
echo -e "  \e[93mCTRL\e[0m + \e[95mY\e[0m : Yank"
echo
