---
- name: Setting Up Packages
  become: true
  become_user: root
  block:
    - name: Refreshing Repository
      zypper_repository:
        repo: '*'
        runrefresh: true

    - name: Adding Packman Repository
      block:
        - zypper_repository:
            name: packman
            repo: https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/
            priority: 90
            state: present
            auto_import_keys: true
            runrefresh: true
        - zypper:
            name: '*'
            state: dist-upgrade
            extra_args: '--from packman --allow-vendor-change'

    - name: Adding SublimeText Repository
      block:
        - rpm_key:
            key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
            state: present
        - zypper_repository:
            name: sublime-text
            repo: https://download.sublimetext.com/rpm/stable/x86_64
            state: present
            runrefresh: true

    - name: Adding VSCode Repository
      block:
        - rpm_key:
            key: https://packages.microsoft.com/keys/microsoft.asc
            state: present
        - zypper_repository:
            name: vscode
            repo: https://packages.microsoft.com/yumrepos/vscode
            state: present
            runrefresh: true

    - name: Installing Packages
      zypper:
        state: present
        name:
          - bat
          - bzip2
          - chromium
          - clang
          - clang-checker
          - clang-devel
          - cmake
          - code
          - curl
          - docker
          - docker-compose
          - fd
          - ffmpeg
          - filezilla
          - firefox
          - fzf
          - gcc
          - gcc-c++
          - git
          - git-web
          - go
          - go-doc
          - htop
          - inkscape
          - kalgebra
          - kdevelop5
          - kdevelop5-plugin-clang-tidy
          - kdevelop5-plugin-python3
          - keepassxc
          - kolourpaint
          - libboost_headers-devel
          - libqt5-creator
          - lighttpd
          - make
          - ncdu
          - okteta
          - okular
          - openssh
          - perf
          - perl-CGI
          - picocom
          - python2-pip
          - python3-pip
          - qdirstat
          - qemu
          - qemu-kvm
          - ripgrep
          - sensors
          - socat
          - speedcrunch
          - sublime-text
          - thunderbird
          - trace-cmd
          - tree
          - unzip
          - valgrind
          - vlc
          - wget
          - wireshark-ui-qt
          - yast2-docker
          - yast2-vm
          - zsh
          # - vagrant
          # - virtualbox-qt
          # - yakuake

    - name: Updating All Packages To Latest
      zypper:
        name: "*"
        state: latest

    - name: Upgrading System
      zypper:
        name: "*"
        state: dist-upgrade
        extra_args: "--no-allow-vendor-change --allow-arch-change"

    - name: Adding User To Groups
      user:
        name: "{{ ansible_user }}"
        groups: "{{ item }}"
        append: yes
      with_items:
        - dialout
        - docker
        - kvm

    # - name: Enabling docker Service
    #   systemd:
    #     name: docker
    #     enabled: yes
    #     masked: no

    - name: Changing sysctl
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key : "fs.inotify.max_user_watches", value : 524288 }

    - name: Creating Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/systemd/journald.conf.d

    - name: Copying Files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        force: no
      with_items:
        - { src : "files/fzf-key-bindings",     dst : "/etc/zsh_completion.d/fzf-key-bindings" }
        - { src : "files/journal-storage.conf", dst : "/etc/systemd/journald.conf.d/00-journal-storage.conf" }
        - { src : "files/sys-upgrade",          dst : "/usr/local/bin/sys-upgrade" }

    - name: Changing Files To Executable
      file:
        dest: "{{ item }}"
        mode: a+x
      with_items:
        - /usr/local/bin/sys-upgrade
