---
- name: Setting Up Packages
  become: true
  become_user: root
  block:
    - name: Refreshing Repository
      zypper_repository:
        repo: '*'
        runrefresh: true
  
    - name: Adding Packman Repository
      block:
        - zypper_repository:
            name: packman
            repo: "{{ urls.opensuse.tumbleweed.packman }}"
            priority: 90
            state: present
            auto_import_keys: true
            runrefresh: true
        - zypper:
            name: '*'
            state: dist-upgrade
            extra_args: '--from packman --allow-vendor-change'

    - name: Adding SublimeText Repository
      block:
        - rpm_key:
            key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
            state: present
        - zypper_repository:
            name: sublime-text
            repo: https://download.sublimetext.com/rpm/stable/x86_64
            state: present
            runrefresh: true

    - name: Installing Packages
      zypper:
        state: present
        name:
          - bat
          - bzip2
          - cargo
          - chromium
          - clang
          - clang-checker
          - clang-devel
          - cmake
          - curl
          - docker
          - docker-compose
          - fd
          - ffmpeg
          - filezilla
          - firefox
          - gcc
          - gcc-c++
          - git
          - git-web
          - go
          - go-doc
          - htop
          - inkscape
          - kdevelop5
          - kdevelop5-plugin-clang-tidy
          - kdevelop5-plugin-python3
          - kolourpaint
          - libboost_headers-devel
          - libqt5-creator
          - lighttpd
          - make
          - ncdu
          - okular
          - openssh
          - perl-CGI
          - picocom
          - python2-pip
          - python3-pip
          - qdirstat
          - qemu
          - qemu-kvm
          - ripgrep
          - rust
          - sensors
          - socat
          - speedcrunch
          - sublime-text
          - thunderbird
          - tree
          - unzip
          - valgrind
          - vlc
          - wget
          - yakuake
          - zsh
          # - vagrant
          # - virtualbox

    - name: Adding User To Groups
      user:
        name: "{{ ansible_user }}"
        groups: "{{ item }}"
        append: yes
      with_items:
        - docker
        - kvm

    - name: Updating All Packages To Latest
      zypper:
        name: "*"
        state: latest

    - name: Upgrading System
      zypper:
        name: "*"
        state: dist-upgrade
        extra_args: "--no-allow-vendor-change --allow-arch-change"
