---
- name: Setting Up Packages
  become: true
  become_user: root
  block:
    - name: Installing Packages
      apt:
        state: present
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl

    # - name: Adding SublimeText Repository
    #   block:
    #     - apt_key:
    #         url: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    #         state: present
    #     - apt_repository:
    #         filename: sublime-text
    #         repo: deb https://download.sublimetext.com/ apt/stable/
    #         state: present

    - name: Adding Docker Repository
      block:
        - apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - apt_repository:
            filename: docker
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
            state: present

    - name: Installing Packages
      apt:
        state: present
        update_cache: yes
        name:
          - aptitude
          - bzip2
          - chromium-browser
          - clang
          - clang-format
          - clang-tidy
          - cmake
          - curl
          - docker
          - docker-compose
          - ffmpeg
          - filezilla
          - firefox
          - g++
          - gcc
          - git
          - htop
          - inkscape
          - libboost-all-dev
          - lm-sensors
          - make
          - okular
          - openssh-server
          - picocom
          - python-pip
          - python3-pip
          - qemu
          - qemu-kvm
          - socat
          - speedcrunch
          # - sublime-text
          - thunderbird
          - tree
          - unzip
          - valgrind
          - vlc
          - wget
          - zsh

    - name: Adding User To Groups
      user:
        name: "{{ ansible_user }}"
        groups: "{{ item }}"
        append: yes
      with_items:
        - docker
        - kvm

    - name: Updating All Packages To Latest
      apt:
        name: "*"
        state: latest

    - name: Removing Useless Packages From The Cache
      apt:
        autoclean: yes

    - name: Removing Dependencies That Are No Longer Required
      apt:
        autoremove: yes
