- name: Creating Directory Structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.cargo/bin

- name: Installing rust
  block:
    - shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - shell: . ~/.cargo/env && rustup component add clippy rustfmt

# --force is used because without it and the package is already installed,
# cargo will return error.
- name: Installing cargo third-party Subcommands
  shell: . ~/.cargo/env && cargo install --force {{ item }}
  with_items:
    - cargo-audit
    - cargo-deps
    - cargo-expand
    - cargo-release

- name: Installing vscode Extensions
  command: code --install-extension "{{ item }}"
  with_items:
    - rust-lang.rust

- name: Copying Files
  template:
    backup: yes
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  with_items:
    - { src: files/cargo-config , dst: ~/.cargo/config }
