---
- name: Creating Directory Structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/pet
    - ~/.local/bin
    - ~/.ssh
    - ~/bin
    - ~/work/media/images
    - ~/work/media/videos
    - ~/work/others
    - ~/work/programming/projects
    - ~/work/programming/sources
    - ~/work/tmp
    - ~/work/tools
    - ~/work/vms
    - ~/work/warehouse

- name: Creating ~/work/{documents, downloads}
  block:
    - name: Moving Files
      command: mv "{{ item.src }}" "{{ item.dst }}"
      args:
        creates: "{{ item.dst }}"
      with_items:
        - { src: "~/Documents", dst: "~/work/documents" }
        - { src: "~/Downloads", dst: "~/work/downloads" }

    - name: Creating Symlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.symlink }}"
        state: link
      with_items:
        - { src: "~/work/documents", symlink: "~/Documents" }
        - { src: "~/work/downloads", symlink: "~/Downloads" }
  
- name: Downloading FireFox And ThunderBird
  block:
    - command: wget -O firefox.tar.bz2 https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US
      args:
        chdir: ~/work/tools
        creates: firefox.tar.bz2
      when: download_firefox | bool
    - command: wget -O thunderbird.tar.bz2 https://download.mozilla.org/?product=thunderbird-beta-latest-SSL&os=linux64&lang=en-US
      args:
        chdir: ~/work/tools
        creates: thunderbird.tar.bz2
      when: download_thunderbird | bool

- name: Oh-My-Zsh
  block:
    - git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh
    - git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
      become: true
      become_user: root

- name: Installing vscode Extensions
  command: code --install-extension "{{ item }}"
  with_items:
    - bungcip.better-toml
    - eamodio.gitlens
    - lextudio.restructuredtext
    - ms-azuretools.vscode-docker
    - ms-python.python
    - vscode-icons-team.vscode-icons

- name: Copying Files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - { src: "files/commands.sh.j2", dst: "~/commands.sh"      , mode: 'a+x' }
    - { src: "files/gapull"        , dst: "~/bin/gapull"       , mode: 'a+x' }
    - { src: "files/gapush"        , dst: "~/bin/gapush"       , mode: 'a+x' }
    - { src: "files/zsh-shortcuts" , dst: "~/bin/zsh-shortcuts", mode: 'a+x' }
    - { src: "files/ssh-config"    , dst: "~/.ssh/config"      , mode: '0600' }
    - { src: "files/curlrc"              , dst: "~/.curlrc" }
    - { src: "files/gdbinit"             , dst: "~/.gdbinit" }
    - { src: "files/gitconfig.j2"        , dst: "~/.gitconfig" }
    - { src: "files/gitmessage"          , dst: "~/.gitmessage" }
    - { src: "files/pet-snippets.toml.j2", dst: "~/.config/pet/snippet.toml" }
    - { src: "files/pet.zsh"             , dst: "~/.pet.zsh" }
    - { src: "files/psqlrc"              , dst: "~/.psqlrc" }
    - { src: "files/tmux.conf"           , dst: "~/.tmux.conf" }
    - { src: "files/vimrc"               , dst: "~/.vimrc" }
    - { src: "files/wgetrc"              , dst: "~/.wgetrc" }
    - { src: "files/zprofile"            , dst: "~/.zprofile" }
    - { src: "files/zshenv"              , dst: "~/.zshenv" }
    - { src: "files/zshrc"               , dst: "~/.zshrc" }
